package eu.opencloud.android.next.core.designsystem.theme

import androidx.compose.ui.graphics.Color

object OpenCloudColor {
    val DocumentPaper = Color(0xFFFFFFFF)
    val Background = Color(0xFFFFFFFF)
    val Chrome = Color(0xFF20434F)
    val BrandMark = Color(0xFFA9B8E8)
    val BrandWordmark = Color(0xFF405080)
    val Error = Color(0xFFBA1A1A)
    val ErrorContainer = Color(0xFFFFDAD6)
    val OnBackground = Color(0xFF191C1D)
    val OnChrome = Color(0xFFFFFFFF)
    val OnError = Color(0xFFFFFFFF)
    val OnErrorContainer = Color(0xFF410002)
    val OnPrimary = Color(0xFFFFFFFF)
    val OnPrimaryContainer = Color(0xFF001F28)
    val OnSecondary = Color(0xFFFFFFFF)
    val OnSecondaryContainer = Color(0xFF071E26)
    val OnSurface = Color(0xFF191C1D)
    val OnSurfaceVariant = Color(0xFF40484C)
    val Outline = Color(0xFF70787C)
    val OutlineVariant = Color(0xFFBFC8CC)
    val Primary = Color(0xFF00677F)
    val PrimaryContainer = Color(0xFFB7EAFF)
    val ResourceFolder = Color(0xFFFFB423)
    val Scrim = Color(0xFF000000)
    val Secondary = Color(0xFF20434F)
    val SecondaryContainer = Color(0xFFCFE6F1)
    val Surface = Color(0xFFFFFFFF)
    val SurfaceContainer = Color(0xFFF6F8FA)
    val SurfaceContainerHigh = Color(0xFFF2F4F5)
    val SurfaceContainerHighest = Color(0xFFECEEF0)
    val SurfaceContainerLow = Color(0xFFFBFCFE)
    val SurfaceDim = Color(0xFFD8DADC)
    val SurfaceVariant = Color(0xFFDBE4E8)
    val Tertiary = Color(0xFF5A5C7E)
    val TertiaryContainer = Color(0xFFE0E0FF)
    val Transparent = Color(0x00000000)
}
