syntax = "proto3";

option java_package = "eu.opencloud.android.next.core.datastore.proto";
option java_multiple_files = true;

message AppSettings {
  enum BrowserLayout {
    BROWSER_LAYOUT_UNSPECIFIED = 0;
    DEFAULT_TABLE = 1;
    CONDENSED_TABLE = 2;
    TILES = 3;
  }

  BrowserLayout browser_layout = 1;
  string active_account_id = 2;
  int32 cache_retention_days = 3;
  bool local_diagnostics_enabled = 4;
  enum Appearance {
    SYSTEM = 0;
    LIGHT = 1;
    DARK = 2;
  }
  Appearance appearance = 5;
  int32 temporary_copy_retention_hours = 6;
  bool hide_file_size = 7;
  bool hide_modified_date = 8;
  bool hide_file_extensions = 9;
  bool show_hidden_files = 10;
}
